import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

test('built ITEMX CODEX plugin is API v3 and owns both UI and pipeline hooks', async () => {
  const source = await readFile(resolve(root, 'dist/itemx2.plugin.js'), 'utf8');
  assert.match(source, /^\/\/@name itemx2$/m);
  assert.match(source, /^\/\/@api 3\.0/m);
  assert.match(source, /^\/\/@version 2\.0\.3$/m);
  assert.match(source, /^\/\/@display-name ITEMX CODEX · v2\.0\.3$/m);
  assert.match(source, /^\/\/@description World Inventory & Encounter Archive$/m);
  assert.match(source, /^\/\/@update-url https:\/\/raw\.githubusercontent\.com\/canister2668\/itemx2\/refs\/heads\/main\/dist\/itemx2\.plugin\.js$/m);
  assert.match(source, /const ITEMX_VERSION_LABEL = "2\.0\.3"/);
  assert.match(source, /ITEMX CODEX · \$\{ITEMX_VERSION_LABEL\}/);
  assert.equal(source.includes('preview.45'), false);
  assert.match(source, /addRisuReplacer\('beforeRequest'/);
  assert.match(source, /addRisuReplacer\('afterRequest'/);
  assert.match(source, /addRisuScriptHandler\('output'/);
  assert.match(source, /addRisuScriptHandler\('display'/);
  assert.match(source, /addRisuScriptHandler\('process', processHandler\)/);
  assert.match(source, /removeRisuScriptHandler\('process', processHandler\)/);
  assert.match(source, /function processTransportStripper\(content\)/);
  assert.match(source, /content: processTransportStripper\(message\.content\)/);
  assert.match(source, /function requestEndsWithModelTurn\(messages\)/);
  assert.match(source, /Array\.isArray\(last\.multimodals\) && last\.multimodals\.length > 0/);
  assert.match(source, /return requestEndsWithModelTurn\(messages\) \? \[\.\.\.messages, protocol\] : \[protocol, \.\.\.messages\]/);
  assert.equal(source.includes('ITEMXCodex.requestView(ITEMXCore.requestView(message.content))'), false);
  assert.match(source, /API method addRisuChatListener not found/);
  assert.match(source, /runtime\.hooks\.listener = 'unsupported'/);
  assert.match(source, /scheduleLegacyCommitRecovery/);
  assert.match(source, /연결 및 권한/);
  assert.match(source, /ITEMX CODEX 연결 및 권한 확인 완료/);
  assert.match(source, /async function callOptionalRisuApi\(name, \.\.\.args\)/);
  assert.equal(/Risuai\.(?:alertNormal|alertError|alertConfirm|alert)\b/.test(source), false, 'undocumented host alert APIs must never be called directly');
  assert.match(source, /ITEMX CODEX 초기화 중…/);
  assert.match(source, /itemx2-boot-card/);
  assert.match(source, /itemx2-feedback-success/);
  assert.match(source, /activeRootTab: 'inventory'/);
  assert.match(source, /tab === 'bestiary' && loaded\.encountersEnabled \? await loadCodexPortraits/);
  assert.match(source, /선택한 탭만 준비하고 있답니다/);
  assert.match(source, /itemx-body-scrolling/);
  assert.match(source, /\['pointerdown', beginBodyScrollEffects\]/);
  assert.match(source, /\['scroll', continueBodyScrollEffects\]/);
  assert.match(source, /\['scrollend', \(\) => endBodyScrollEffects\(40\)\]/);
  assert.match(source, /addEventListener\(type, handler, true\)/);
  assert.match(source, /function continueBodyScrollEffects\(\)[\s\S]*activateBodyScrollEffects\(\);[\s\S]*endBodyScrollEffects\(220\)/);
  assert.match(source, /bodyFxScrollTimer = globalThis\.setTimeout/);
  assert.match(source, /const ITEMX_ROOT_PAGE_SIZE = 16/);
  assert.equal(source.includes('.slice(-512)'), false, 'message event replay must never drop live refs by count');
  assert.equal(source.includes('.slice(-256)'), false, 'manual replay must never drop authoritative events by count');
  assert.equal(source.includes('encodedLedger.length > 393216'), false, 'message events must not be discarded to satisfy a byte cap');
  assert.match(source, /\$__itemx2_checkpoint/);
  assert.match(source, /function checkpointReplay\(chat\)/);
  assert.match(source, /prefixMarkerFingerprint/);
  assert.match(source, /ITEMX_CHECKPOINT_TAIL_MESSAGES = 32/);
  assert.match(source, /p: view\.power, q: view\.required, u: view\.durability, c: view\.cost, o: view\.possession, l: view\.location/);
  assert.match(source, /runtime\.eventPayloads\.get\(`item:\$\{ref\}`\) \|\| inlineViewPayload\(inline, 'item'\)/);
  assert.match(source, /if \(!open\) return `\$\{rootBadgeHtml\(\)\}.*itemx2-open-loading/);
  assert.match(source, /const ITEMX_UPDATE_CHECK_MS = 30 \* 60 \* 1000/);
  assert.match(source, /headers: \{ Range: 'bytes=0-2047' \}/);
  assert.match(source, /itemx2-update-indicator/);
  assert.match(source, /compareVersions\(latest, ITEMX_PLUGIN_VERSION\) > 0/);
  assert.equal(source.includes('installRootItemDetailClicks'), false);
  const rootRouter = source.slice(source.indexOf('async function installRootClickRouter'), source.indexOf('async function openRootInventory'));
  assert.equal((rootRouter.match(/addEventListener\('click'/g) || []).length, 1);
  assert.match(rootRouter, /rootClickBindings = \[\{ type: 'click', id, capture: true \}\]/);
  assert.match(rootRouter, /itemx2-root-detail-body-/);
  assert.match(source, /ITEMX CODEX · 권한 및 설정/);
  assert.match(source, /itemx2-host-settings/);
  assert.match(source, /hostPluginSettingsVisible/);
  assert.match(source, /보조 모델 상태/);
  assert.match(source, /itemx2-setting-aux-run/);
  assert.match(source, /itemx2-setting-rarity/);
  assert.match(source, /data-action="rarity-mode"/);
  assert.match(source, /rarityMode:\$\{id\}/);
  assert.match(source, /effectsEnabled:\$\{id\}/);
  assert.match(source, /fontScale:\$\{id\}/);
  assert.match(source, /itemx2-setting-font-\$\{value\}/);
  assert.match(source, /syncRootFontScale/);
  const fontSetter = source.slice(source.indexOf('async function setFontScale'), source.indexOf('const AUX_LABELS'));
  assert.equal(fontSetter.includes('openRootInventory'), false);
  assert.equal(fontSetter.includes('setInnerHTML'), false);
  assert.equal(fontSetter.includes('generation'), false);
  assert.match(source, /itemx2-codex-fx/);
  assert.match(source, /function skillTheme\(skill\)/);
  assert.match(source, /function skillRankTier\(rank, rarityMode = 'world'\)/);
  assert.match(source, /ITEMXRenderer\.renderSkillFx/);
  assert.match(source, /function encounterThreatLevel\(value\)/);
  assert.match(source, /itemx2-skill-theme-fire\.itemx2-skill-list-fx/);
  assert.match(source, /itemx2-skill-theme-ice\.itemx2-skill-list-fx/);
  assert.match(source, /itemx2-skill-theme-lightning\.itemx2-skill-list-fx/);
  assert.match(source, /itemx2-skill-theme-dark\.itemx2-skill-list-fx/);
  assert.match(source, /itemx2-skill-theme-light\.itemx2-skill-list-fx/);
  assert.match(source, /itemx2-skill-theme-arcane\.itemx2-skill-list-fx/);
  assert.match(source, /itemx2-encounter-theme-humanoid/);
  assert.match(source, /itemx-monster-portrait\{filter:saturate\(\.86\) contrast\(1\.06\)\}/);
  assert.match(source, /\.itemx2-effects-off \.itemx2-codex-fx\{display:none!important/);
  assert.match(source, /@media\(prefers-reduced-motion:reduce\)\{\.itemx2-codex-fx,\.itemx2-codex-fx \*,\.itemx2-skill-weapon-fx,\.itemx2-skill-weapon-fx \*\{animation:none!important\}\}/);
  assert.match(source, /const codexListFx = \(domain, classes\) => `<span class="itemx2-codex-fx/);
  assert.match(source, /const codexHeroFx = \(domain\) => `<span class="itemx2-codex-fx[^`]+<i><\/i><b><\/b><em><\/em><\/span>`/);
  const materialFx = source.slice(source.indexOf('.itemx2-codex-fx{'), source.indexOf('const rootDrawerStyle'));
  assert.equal(materialFx.includes('will-change'), false);
  assert.equal(materialFx.includes('itemx2-codex-spin'), true);
  assert.match(source, /itemx2-setting-effects/);
  assert.match(source, /data-action="effects"/);
  assert.match(source, /시각 이펙트/);
  assert.match(source, /settingsCache: new Map\(\)/);
  assert.match(source, /settingsLoadPromises: new Map\(\)/);
  assert.match(source, /await outputSettings\(initial\.character\)/);
  assert.match(source, /ITEMX Rarity Policy: FORCED/);
  assert.match(source, /rarity=empyrean even if the setting calls that grade Epic/);
  assert.match(source, /const settings = await outputSettings\(loaded\.character\)/);
  const auxRarityPrompt = source.slice(source.indexOf('async function recoverAuxiliaryOutputNow'), source.indexOf('async function runItemModel'));
  assert.match(auxRarityPrompt, /protocolForSettings\(settings, ctx\.character, moduleAssets\)/);
  const manualRarityPrompt = source.slice(source.indexOf('async function runItemModel'), source.indexOf('function mainRequestType'));
  assert.match(manualRarityPrompt, /itemxProtocolText\(settings\.rarityMode\)/);
  const mainRarityPrompt = source.slice(source.indexOf('const beforeRequest'), source.indexOf('async function processOutput'));
  assert.match(mainRarityPrompt, /protocolForSettings\(settings, loaded\.character, moduleAssets\)/);
  assert.match(source, /moduleAssetsEnabled/);
  assert.match(source, /Risuai\.getDatabase\(\['modules', 'enabledModules', 'moduleIntergration', 'personas', 'selectedPersona'\]\)/);
  assert.match(source, /모듈 에셋 권한이 허용되지 않았습니다\. 조우 초상화는 이모지로 표시됩니다/);
  assert.match(source, /const visual = portrait \? `<img[^`]+` : `<span class="itemx2-codex-glyph">/);
  assert.match(source, /runtime\.moduleAssetCache = \{ key, at: Date\.now\(\), rows: \[\] \}/);
  assert.match(source, /보조 검사 완료/);
  assert.match(source, /connectionBusy: false/);
  assert.match(source, /async function updateConnectionUi/);
  const connectionHandler = source.slice(source.indexOf('const connect ='), source.indexOf('const auxRun ='));
  assert.match(connectionHandler, /if \(runtime\.connectionBusy\) return/);
  assert.match(connectionHandler, /await updateConnectionUi\(\)/);
  assert.equal(connectionHandler.includes('openRootInventory'), false);
  assert.match(source, /settingChangeBusy: false, auxRecoveryPromise: null/);
  assert.match(source, /보조 모델이 90초 안에 응답하지 않았습니다/);
  assert.match(source, /if \(runtime\.auxRecoveryPromise\) return runtime\.auxRecoveryPromise/);
  assert.match(source, /automaticAuxReady\(ctx\.chat, index, source\)/);
  assert.match(source, /if \(runtime\.auxActive > 0 \|\| runtime\.auxRecoveryPromise\) return/);
  assert.match(source, /runtime\.auxActive === 0 && !runtime\.auxRecoveryPromise/);
  assert.match(source, /await rememberAuxiliaryZero\(ctx, guardKey\)/);
  assert.match(source, /ITEMX context-aware auxiliary regeneration pass/);
  assert.match(source, /TRIGGERING USER TURN/);
  assert.match(source, /RECENT NARRATIVE CONTEXT/);
  assert.match(source, /COMMITTED ASSISTANT OUTPUT \(visible narrative only\)/);
  assert.match(source, /if \(\/itemx\/i\.test\(key\)/);
  assert.match(source, /runtime\.uiRemountAfter = Date\.now\(\) \+ 1200/);
  assert.match(source, /Date\.now\(\) < runtime\.uiRemountAfter/);
  const rootToggleHandler = source.slice(source.indexOf("const toggle = runtime.mainDoc"), source.indexOf("const main = runtime.mainDoc"));
  assert.match(rootToggleHandler, /updateRootSettingButton/);
  assert.equal(rootToggleHandler.includes('openRootInventory'), false);
  assert.equal(rootToggleHandler.includes('recoverAuxiliaryOutput'), false);
  const iframeAuxHandler = source.match(/root\.querySelector\('\[data-action="aux-output"\]'\)[^\n]+/)?.[0] || '';
  assert.equal(iframeAuxHandler.includes('recoverAuxiliaryOutput'), false);
  const auxRunHandler = source.slice(source.indexOf('const auxRun ='), source.indexOf('for (const [key, label] of BADGE_POSITIONS)'));
  assert.match(auxRunHandler, /recoverAuxiliaryOutput\(\{ force: true \}\)/);
  assert.equal(auxRunHandler.includes('openRootInventory'), false);
  assert.match(source, /runButton\.setTextContent\(runtime\.auxActive > 0 \? '처리 중…' : '지금 검사'\)/);
  assert.match(source, /\.itemx2-root-inventory\{display:flex;flex:1;min-height:0;flex-direction:column;overflow:hidden\}/);
  assert.match(source, /\.itemx2-root-inventory>\.itemx-body\{flex:1;min-height:0;overflow-x:hidden;overflow-y:auto/);
  assert.match(source, /itemx2-root-detail-body-\$\{index\}/);
  assert.equal(source.includes('installRootItemDetailClicks'), false);
  assert.match(source, /detail\.setInnerHTML\(itemDetailHtml\(detailItems\[index\]\)\)/);
  assert.match(source, /async function hydrateCheckedItemDetail\(loaded\)/);
  assert.match(source, /querySelector\(`#itemx2-detail-\$\{index\}:checked`\)/);
  assert.match(source, /await delay\(0\);\s*if \(await hydrateCheckedItemDetail\(loaded\)\) return/);
  assert.match(source, /async function hydrateCheckedCodexDetail\(domain, loaded\)/);
  assert.match(source, /itemx2-\$\{domain\}-entry-choice:checked ~ \.x-risu-itemx2-\$\{domain\}-detail/);
  assert.match(source, /itemx2-monster-entry-choice/);
  assert.match(source, /codexDetailCacheKey\(domain, entity, portrait, loaded\.rarityMode\)/);
  const rootInventoryBuilder = source.slice(source.indexOf('function rootInventoryHtml'), source.indexOf('function rootInventoryRegions'));
  assert.equal(rootInventoryBuilder.includes("${skillPageHtml("), false, 'SafeDOM skill list must not pre-render full detail pages');
  assert.equal(rootInventoryBuilder.includes("${monsterPageHtml("), false, 'SafeDOM encounter list must not pre-render full detail pages');
  assert.match(rootInventoryBuilder, /상세 정보를 불러오는 중…/);
  assert.match(source, /Array\.from\(\{ length: Math\.min\(4, monsters\.length\) \}, \(\) => loadNextPortrait\(\)\)/);
  assert.equal(source.includes('Promise.all(monsters.map'), false);
  assert.match(source, /runtime\.hooks\.listener === true \? 45000 : 4500/);
  assert.match(source, /addRisuChatListener\('output', \(\) => \{ void scheduleCommittedOutputSync\(\); \}\)/);
  const outputSync = source.slice(source.indexOf('function scheduleCommittedOutputSync'), source.indexOf('function armCatchUpWatchdog'));
  assert.equal((outputSync.match(/ensureRootInventory\(\)/g) || []).length, 1);
  assert.match(source, /now - runtime\.hostSettingsCache\.at < 750/);
  assert.match(source, /\.itemx2-threat-3 \.itemx2-encounter-hero-fx\{filter:brightness/);
  assert.equal(/\.itemx2-threat-3\{filter:brightness/.test(source), false);
  assert.match(source, /\.itemx2-encounter-ended \.itemx-monster-portrait\{opacity:\.72;filter:grayscale\(\.82\) saturate\(\.28\) contrast\(1\.04\)\}/);
  assert.match(source, /\.itemx-monster-hero\.itemx2-encounter-ended\{border-color:#3f4652;background:radial-gradient/);
  assert.match(source, /\.itemx-monster-hero\.itemx2-encounter-ended::before\{[^}]*animation-play-state:paused!important\}/);
  assert.match(source, /\.itemx-monster-hero\.itemx2-encounter-ended::after,\.itemx2-encounter-ended \.itemx2-encounter-hero-fx::after\{background:linear-gradient\(90deg,transparent,#8b94a3,transparent\);[^}]*animation-play-state:paused!important\}/);
  assert.match(source, /querySelector\(`\.x-risu-\$\{className\}`\)[\s\S]*querySelector\(`\.\$\{className\}`\)/);
  assert.equal(source.includes('renderCard(detailItems[index]'), false);
  assert.match(source, /const ITEMX_CODEX_INLINE_STYLE =/);
  assert.match(source, /function codexInlineEventHtml\(payload, motion = 'full'\)/);
  assert.match(source, /NEW SKILL ARCHIVED/);
  assert.match(source, /itemx2-inline-quick/);
  assert.match(source, /itemx2-inline-appraisal/);
  assert.match(source, /function codexInlineAppraisalStyle\(entity, domain\)/);
  assert.match(source, /itemx2-inline-tier/);
  assert.match(source, /최근 전투 결과/);
  assert.match(source, /width:min\(400px,calc\(100% - 8px\)\)/);
  assert.match(source, /\.itemx2-inline-event \.itemx2-inline-state\{display:inline-flex/);
  assert.match(source, /ENCOUNTER RESOLVED/);
  assert.match(source, /!inline && !runtime\.latestMarkers\.has\(`CODEX2@\$\{ref\}`\)/);
  assert.match(source, /markerHtmlCache: new Map\(\)/);
  assert.equal(/renderCard\(item, \{ motion: index < 2/.test(source), false);
  const displayHandler = source.slice(source.indexOf('const displayHandler ='), source.indexOf('async function installMainStyle'));
  assert.equal(displayHandler.includes("motion = cards < 2 ? 'full' : 'off'"), false);
  assert.match(displayHandler, /const markerMotion = \(key\) =>/);
  assert.match(displayHandler, /return runtime\.latestMarkers\.has\(key\) \? 'lite' : 'off'/);
  assert.match(displayHandler, /renderPayload\(`item:\$\{code\}`, payload, motion\)/);
  assert.match(displayHandler, /renderPayload\(`item-ref:\$\{ref\}`, payload, motion\)/);
  assert.match(source, /cachedOrRebuildCurrent\(\)/);
  assert.match(source, /portraitCache: new Map\(\)/);
  assert.match(source, /mainStylePosition === runtime\.badgePosition/);
  assert.match(source, /content-visibility:auto/);
  assert.match(source, /async function installBodyEffectGovernor/);
  assert.equal(source.includes('getBoundingClientRect();\n        const active = rect.bottom'), false);
  assert.match(source, /chattext\.x-risu-itemx-body-scrolling/);
  assert.match(source, /animation-play-state:paused!important/);
  assert.match(source, /itemx2-inline-main::before/);
  assert.match(source, /mix-blend-mode:normal!important/);
  assert.match(source, /contain-intrinsic-size:auto 128px/);
  assert.match(source, /outputSyncDeferred = true/);
  assert.match(source, /if \(runtime\.bodyFxScrollActive\) \{\s*runtime\.hostSyncDeferred = true;\s*if \(runtime\.hostSyncTimer\) globalThis\.clearTimeout/);
  assert.match(source, /itemx2-effects-off/);
  assert.match(source, /itemx-codex-scan\{0%,100%\{opacity:\.2;transform:translate3d/);
  assert.equal(/itemx-codex-scan\{0%,100%\{top:/.test(source), false);
  assert.match(source, /✨ ARCANE SKILL RECORD/);
  assert.match(source, /⚔️ ENCOUNTER ARCHIVE/);
  assert.match(source, /⚔️ 최근 전투 결과/);
  assert.match(source, /latest completed combat result only/);
  assert.match(source, /Preserve the previous outcome when a new encounter begins/);
  assert.match(source, /touch-action:pan-y;-webkit-overflow-scrolling:touch/);
  assert.equal(source.includes('registerButton('), false);
  assert.match(source, /registerSetting\('ITEMX CODEX · 권한 및 설정', openSettingsFromRisuMenu/);
  assert.equal(source.includes('requestPermission: false'), false);
  assert.match(source, /requestPluginPermission\('replacer'\)/);
  assert.match(source, /runtime\.permissions\.replacer = permission === true/);
  assert.match(source, /return runtime\.permissions\.replacer/);
  assert.equal(source.includes('itemx2PermissionVersion'), false);
  assert.match(source, /itemx2-native-badge/);
  assert.match(source, /showContainer\(runtime\.compactContainer \? 'floating' : 'fullscreen'\)/);
  assert.match(source, /resizeContainer\(panelHeight, panelWidth\)/);
  assert.match(source, /resizeContainer unavailable; using bounded fullscreen fallback/);
  assert.match(source, /runtime\.compactContainer \? 'floating' : 'fullscreen'/);
  assert.match(source, /itemx-plugin-stage-fallback/);
  assert.match(source, /x-itemx2-badge="launcher"/);
  assert.match(source, /width="48" height="176"/);
  assert.equal(source.includes('<b>INVENTORY</b>'), false);
  assert.match(source, /overflow:\s*hidden/);
  assert.match(source, /@keyframes itemx-plugin-panel-in/);
  assert.match(source, /@keyframes itemx-plugin-panel-out/);
  assert.match(source, /panelOpen: false, panelTransition: 0/);
  assert.match(source, /transition !== runtime\.panelTransition \|\| runtime\.panelOpen/);
  assert.equal(/pluginStorage\.setItem\([^\n]*(panelOpen|inventoryOpen)/.test(source), false);
  const outputPipeline = source.slice(source.indexOf('async function processOutput'), source.indexOf('const afterRequest'));
  assert.equal(outputPipeline.includes('showContainer'), false);
  assert.equal(outputPipeline.includes('hideContainer'), false);
  assert.equal(outputPipeline.includes('recoverAuxiliaryOutput'), false);
  assert.equal(outputPipeline.includes('setTimeout'), false);
  assert.equal(source.includes('persist: true'), false);
  assert.match(source, /const loaded = await rebuildCurrent\(\);\s*if \(loaded\?\.encountersEnabled && loaded\?\.lorebookEncounterEnabled\) await scanLorebookEncounters\(\{ silent: true \}\);\s*await catchUpLatestOutput/);
  assert.match(source, /getCurrentLorebookEntries/);
  assert.match(source, /lorebookEncounterEnabled:\$\{id\}/);
  assert.match(source, /조우 로어북 보완/);
  assert.match(source, /활성 모듈 로어북/);
  assert.match(source, /automaticAuxSettled\(ctx, index, source\)/);
  assert.match(source, /auxCandidateChecks >= 2/);
  assert.match(source, /async function catchUpLatestOutput\(\{ syncUi = true \} = \{\}\)/);
  assert.match(source, /async function repairCommittedTransport\(ctx, index, source\)/);
  assert.match(source, /runtime\.catchUpFingerprint = fingerprint/);
  assert.match(source, /visible-\$\{auxiliarySemanticHash\(source\)\}/);
  assert.match(source, /ITEMX_MESSAGE_EVENT_KEY/);
  assert.match(source, /compactRefMarker\(prefix, ref, payload, domain\)/);
  assert.match(source, /embeddedViewCode/);
  assert.match(source, /inlineViewPayload\(inline, 'item'\)/);
  assert.match(source, /ITEMX CODEX · 기록 복원 중/);
  assert.match(source, /runtime\.catchUpFailedFingerprint = fingerprint/);
  assert.match(source, /runtime\.catchUpRetryAt = Date\.now\(\) \+ Math\.min\(120000/);
  assert.equal(source.includes("settings.auxOutput === 'missing' && sourceEvents.length"), false);
  assert.match(source, /removeRisuReplacer\('beforeRequest', beforeRequest\)/);
  assert.match(source, /removeRisuReplacer\('afterRequest', afterRequest\)/);
  assert.match(source, /validationRegistry = ITEMXCore\.clone\(snapshot\.registry\)/);
  assert.match(source, /const interval = runtime\.hooks\.listener === true \? 45000 : 4500/);
  assert.match(source, /setInterval\(\(\) => \{\s*void catchUpLatestOutput\(\)/);
  assert.match(source, /including an earlier misspelling/);
  assert.match(source, /itemPatch op=merge/);
  assert.match(source, /const ITEMX_AUX_PROMPT_REVISION = 2/);
  assert.match(source, /allowPlugins:\s*true/);
  assert.match(source, /AUX_PROVIDER_UNAVAILABLE/);
  assert.match(source, /runtime\.auxProviderUnavailable && !force/);
  assert.match(source, /positionMarkersByNarrative/);
  assert.match(source, /preserve every required status\/state\/route trailer/);
  assert.match(source, /itemx-oriental-frame/);
  assert.match(source, /itemx-oriental-seal/);
  assert.match(source, /craft-oriental \.affinity-fx/);
  assert.match(source, /const ITEMXCodex/);
  assert.match(source, /itemx2-tab-skills/);
  assert.match(source, /itemx2-tab-bestiary/);
  assert.match(source, /itemx2-codex-entry-choice/);
  assert.match(source, /ARCANE SKILL RECORD/);
  assert.match(source, /ENCOUNTER ARCHIVE/);
  assert.match(source, /itemx-codex-scan/);
  assert.match(source, /itemx2-codex-detail-row/);
  assert.match(source, /itemsEnabled:\$\{id\}/);
  assert.match(source, /skillsEnabled:\$\{id\}/);
  assert.match(source, /encountersEnabled:\$\{id\}/);
  assert.match(source, /setDomainEnabled/);
  assert.match(source, /enabledCodexDomains/);
  assert.match(source, /Enabled domains: \$\{requested\}/);
  assert.match(source, /기능별 추적/);
  assert.match(source, /무기·아이템/);
  assert.match(source, /전투 도감/);
  assert.match(source, /디버그 진단/);
  assert.match(source, /debugEntries\.length > 30/);
  assert.match(source, /data-action="debug-toggle"/);
  assert.match(source, /ITEMX CODEX · ACTIVE CONTEXT/);
  assert.match(source, /AVAILABLE PORTRAIT ASSET NAMES/);
  assert.match(source, /Risuai\.readImage\(asset\.id\)/);
  assert.match(source, /image\/avif/);
  assert.match(source, /ITEMXCodex\.assetForEntity\(catalog, monster, narrative\)/);
  assert.match(source, /loaded\.portraits\?\.\[monster\.id\]/);
  assert.match(source, /const ITEMXQuality =/);
  assert.match(source, /state: unresolvedPartials\.length \|\| rejectedIds\.length \? 'partial_final' : 'complete'/);
  assert.match(source, /state: 'rejected'/);
  assert.match(source, /아이템 상세정보 보완 중/);
  assert.ok(source.length < 510000, 'plugin bundle must stay compact with checkpoint replay and fixed-layer inline appraisal cards');
  assert.equal(source.includes('itemx-batch'), false);
  assert.match(source, /runtime\.remountTimer = globalThis\.setInterval/);
  assert.match(source, /\}, 1200\)/);
  assert.match(source, /now - runtime\.homeProbeAt < 10000/);
  assert.match(source, /async function cachedRequestState\(\)/);
  assert.match(source, /cached\.replayFingerprint === replaySourceFingerprint\(active\.chat\)/);
  assert.match(source, /const loaded = await cachedRequestState\(\)/);
  assert.match(source, /async function managerRowIndexAtY\(count, clientY\)/);
  assert.match(source, /const index = \(low \+ high\) >> 1/);
  assert.match(source, /itemx2-manager-row-\$\{index\}/);
  assert.match(source, /const value = scalar\(body, a, key\)/);
  assert.match(source, /createMutationObserver/);
  assert.equal(source.includes('hostSettingsTimer'), false);
  const ensureRoot = source.slice(source.indexOf('async function ensureRootInventory'), source.indexOf('async function loadCodexPortraits'));
  assert.ok(ensureRoot.indexOf('const active = await context()') < ensureRoot.indexOf('runtime.auxActive > 0'));
  assert.match(source, /async function resetRuntimeForContext\(active\)/);
  const resetRuntime = source.slice(source.indexOf('async function resetRuntimeForContext'), source.indexOf('async function ensureRootInventory'));
  assert.equal(resetRuntime.includes('runtime.eventPayloads = new Map()'), false);
  assert.match(resetRuntime, /refreshLatest\(active\?\.chat/);
  assert.match(source, /runtime\.markerHtmlCache\.clear\(\)/);
  assert.match(source, /runtime\.lastDomError/);
  assert.match(source, /await delay\(300\)/);
  assert.equal(source.includes("registerSetting('ITEMX CODEX · 설정', () => openInventory('settings')"), false);
  assert.equal(source.includes("showContainer('fullscreen')"), false);
  assert.match(source, /async function openRootInventory/);
  assert.match(source, /x-itemx2-drawer/);
  assert.match(source, /pointer-events:none/);
  assert.match(source, /await doc\.createElement\('style'\)/);
  const rootInventory = source.slice(source.indexOf('async function openRootInventory'), source.indexOf('function matches'));
  assert.equal(rootInventory.includes('showContainer'), false);
  assert.equal(rootInventory.includes("'fullscreen'"), false);
  assert.match(source, /button\[aria-label="ITEMX"\]/);
  assert.match(source, /badgePosition/);
  assert.match(source, /badgePosition: 'rm'/);
  assert.match(source, /positions\[runtime\.badgePosition\] \|\| positions\.rm/);
  assert.match(source, /좌하/);
  assert.match(source, /우상/);
  assert.match(source, /await runtime\.rootDrawer\.addClass\(`x-risu-itemx2-pos-\$\{key\}`\)/);
  assert.match(source, /drawerAttached = Boolean\(await runtime\.rootDrawer\.getParent\(\)\)/);
  assert.match(source, /styleAttached = Boolean\(await runtime\.mainStyle\.getParent\(\)\)/);
  assert.equal(source.includes('const positionControls ='), false);
  assert.equal(source.includes('itemx2-root-open"'), false);
  assert.match(source, /async function setRootOpen\(open\)/);
  const badgeClick = source.slice(source.indexOf('const routeBadge = async'), source.indexOf('const routeControls = async'));
  assert.ok(badgeClick.indexOf('await setRootOpen(true)') < badgeClick.indexOf('cachedOrRebuildCurrent()'));
  assert.match(badgeClick, /runtime\.rootContentReady && cacheReady/);
  const removeRoot = source.slice(source.indexOf('async function removeRootClickRouter'), source.indexOf('async function mountRootLoading'));
  assert.ok(removeRoot.indexOf('await removeRootClickRouter()') < removeRoot.indexOf('await runtime.rootDrawer.remove()'));
  assert.match(source, /target\.matches\('\[x-itemx2-drawer="owner"\], \[x-itemx2-drawer="owner"\] \*'\)/);
  assert.match(source, /const lookup = buildMessageEventLookup\(latestChat\)/);
  const codexReplay = source.slice(source.indexOf('function rebuildCodexWithLedger'), source.indexOf('function compactMessageTransports'));
  assert.equal(codexReplay.includes('reconcileSkillEvent'), false);
  assert.match(source, /\['avif', 'avis', 'mif1', 'miaf'\]\.includes\(isoBrand\)/);
  assert.match(source, /const regionUpdated = attached && open && runtime\.rootContentReady && await updateRootRegions\(html\)/);
  assert.match(source, /attached = Boolean\(await root\.getParent\(\)\)/);
  assert.match(source, /if \(!attached\) \{\s*await removeRootDrawer\(\)/);
  assert.match(source, /await setRootOpen\(false\)/);
  assert.match(source, /itemx2-root-drawer\.itemx2-is-open \.itemx2-root-panel/);
  const positionHandler = source.slice(source.indexOf('for (const [key, label] of BADGE_POSITIONS)'), source.indexOf("const toggle = runtime.mainDoc"));
  assert.equal(positionHandler.includes('installMainStyle'), true);
  assert.equal(positionHandler.includes('openRootInventory'), false);
  assert.match(source, /data-tab="settings"/);
  assert.match(source, /enabled: enabled !== '0'/);
  const bootstrap = source.slice(source.lastIndexOf('await loadBadgePosition()'), source.indexOf('await Risuai.onUnload'));
  assert.ok(bootstrap.indexOf('registerSetting(') < bootstrap.indexOf('const initial = await context()'));
  assert.ok(bootstrap.indexOf('const initial = await context()') < bootstrap.indexOf('connected = await installPipelineHooks()'));
  assert.match(bootstrap, /runtime\.status = '채팅 진입 대기'/);
  assert.match(source, /const styled = await installMainStyle\(\)/);
  assert.match(source, /getRootDocument\(/);
  assert.match(source, /setChatToIndex\(/);
  assert.match(source, /현재 채팅 ITEMX 기록 제거/);
  assert.match(source, /async function cleanCurrentChatItemx\(\)/);
  assert.match(source, /const CHAT_DATA_KEYS = \[/);
  assert.match(source, /await setEnabled\(ctx\.character, false\)/);
  assert.match(source, /runtime\.cleanupArmedUntil = Date\.now\(\) \+ 7000/);
  assert.match(source, /function reconcileStoredRefViews\(chat, preferredLatestIndex = null\)/);
  assert.match(source, /const keepInline = index === latestIndex/);
  assert.match(source, /\.chattext \.x-risu-itemx-card/);
  assert.equal(source.includes('__ITEMX_'), false);
  assert.equal(source.includes('{{moduleenabled'), false);
  assert.equal(source.includes('risu-trigger='), false);
});

test('guide settings preview is generated from the real root settings renderer', async () => {
  const source = await readFile(resolve(root, 'design/itemx-settings-actual.html'), 'utf8');
  for (const label of ['연결 및 권한', '보조 모델 상태', '기능별 추적', '사이드 배지 위치', '아이템 관리', '현재 봇 ITEMX CODEX', '메인 출력', '보조 출력', '등급 기준', '시각 이펙트', '모듈 에셋 초상화', '글자 크기', '채팅 저장소', '현재 채팅 ITEMX 기록 제거']) assert.match(source, new RegExp(label));
  assert.doesNotMatch(source, /도감 컨텍스트 제한|이름 없는 잡졸|확장 UI 시안/);
  assert.match(source, /ITEMX CODEX · 2\.0\.0/);
});

test('preview uses the same renderer source as the plugin', async () => {
  const preview = await readFile(resolve(root, 'dist/itemx2-preview.html'), 'utf8');
  assert.match(preview, /ITEMXRenderer\.renderCard/);
  assert.match(preview, /ITEMXRenderer\.renderTile/);
  assert.match(preview, /단일 속성/);
  assert.match(preview, /다중 속성/);
});
