import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

test('built ITEMX CODEX plugin is API v3 and owns both UI and pipeline hooks', async () => {
  const source = await readFile(resolve(root, 'dist/itemx2.plugin.js'), 'utf8');
  assert.match(source, /^\/\/@name itemx2$/m);
  assert.match(source, /^\/\/@api 3\.0/m);
  assert.match(source, /^\/\/@version 1\.9\.0-beta\.12$/m);
  assert.match(source, /^\/\/@display-name ITEMX CODEX$/m);
  assert.match(source, /^\/\/@description World Inventory & Encounter Archive$/m);
  assert.match(source, /^\/\/@update-url https:\/\/raw\.githubusercontent\.com\/canister2668\/itemx2\/main\/dist\/itemx2\.plugin\.js$/m);
  assert.match(source, /const ITEMX_VERSION_LABEL = '1\.9 · BETA 12'/);
  assert.match(source, /ITEMX CODEX · \$\{ITEMX_VERSION_LABEL\}/);
  assert.equal(source.includes('preview.45'), false);
  assert.match(source, /addRisuReplacer\('beforeRequest'/);
  assert.match(source, /addRisuReplacer\('afterRequest'/);
  assert.match(source, /addRisuScriptHandler\('output'/);
  assert.match(source, /addRisuScriptHandler\('display'/);
  assert.match(source, /API method addRisuChatListener not found/);
  assert.match(source, /runtime\.hooks\.listener = 'unsupported'/);
  assert.match(source, /scheduleLegacyCommitRecovery/);
  assert.match(source, /연결 및 권한/);
  assert.match(source, /ITEMX CODEX 연결 및 권한 확인 완료/);
  assert.match(source, /ITEMX CODEX 초기화 중…/);
  assert.match(source, /itemx2-boot-card/);
  assert.match(source, /itemx2-feedback-success/);
  assert.match(source, /activeRootTab: 'inventory'/);
  assert.match(source, /tab === 'bestiary' && loaded\.encountersEnabled \? await loadCodexPortraits/);
  assert.match(source, /선택한 탭만 준비하고 있답니다/);
  assert.match(source, /itemx-body-scrolling/);
  assert.match(source, /\['pointerdown', beginBodyScrollEffects\]/);
  assert.match(source, /\['scrollend', \(\) => endBodyScrollEffects\(40\)\]/);
  assert.match(source, /addEventListener\(type, handler, true\)/);
  assert.equal(source.includes("addEventListener('scroll',"), false);
  assert.match(source, /bodyFxScrollTimer = globalThis\.setTimeout/);
  assert.match(source, /const ITEMX_ROOT_PAGE_SIZE = 16/);
  assert.match(source, /if \(!open\) return `\$\{rootBadgeHtml\(\)\}.*itemx2-open-loading/);
  assert.match(source, /const ITEMX_UPDATE_CHECK_MS = 30 \* 60 \* 1000/);
  assert.match(source, /headers: \{ Range: 'bytes=0-2047' \}/);
  assert.match(source, /itemx2-update-indicator/);
  assert.match(source, /compareVersions\(latest, ITEMX_PLUGIN_VERSION\) > 0/);
  assert.equal(source.includes('installRootItemDetailClicks'), false);
  const rootRouter = source.slice(source.indexOf('async function installRootClickRouter'), source.indexOf('async function openRootInventory'));
  assert.equal((rootRouter.match(/addEventListener\('click'/g) || []).length, 1);
  assert.match(rootRouter, /rootClickBindings = \[\{ type: 'click', id, capture: true \}\]/);
  assert.match(rootRouter, /itemx2-root-detail-body-/);
  assert.match(source, /ITEMX CODEX · 권한 및 설정/);
  assert.match(source, /itemx2-host-settings/);
  assert.match(source, /hostPluginSettingsVisible/);
  assert.match(source, /보조 모델 상태/);
  assert.match(source, /itemx2-setting-aux-run/);
  assert.match(source, /itemx2-setting-rarity/);
  assert.match(source, /data-action="rarity-mode"/);
  assert.match(source, /rarityMode:\$\{id\}/);
  assert.match(source, /effectsEnabled:\$\{id\}/);
  assert.match(source, /itemx2-setting-effects/);
  assert.match(source, /data-action="effects"/);
  assert.match(source, /시각 이펙트/);
  assert.match(source, /settingsCache: new Map\(\)/);
  assert.match(source, /settingsLoadPromises: new Map\(\)/);
  assert.match(source, /await outputSettings\(initial\.character\)/);
  assert.match(source, /ITEMX Rarity Policy: FORCED/);
  assert.match(source, /rarity=empyrean even if the setting calls that grade Epic/);
  assert.match(source, /const settings = await outputSettings\(loaded\.character\)/);
  const auxRarityPrompt = source.slice(source.indexOf('async function recoverAuxiliaryOutputNow'), source.indexOf('async function runItemModel'));
  assert.match(auxRarityPrompt, /protocolForSettings\(settings, ctx\.character\)/);
  const manualRarityPrompt = source.slice(source.indexOf('async function runItemModel'), source.indexOf('function mainRequestType'));
  assert.match(manualRarityPrompt, /itemxProtocolText\(settings\.rarityMode\)/);
  const mainRarityPrompt = source.slice(source.indexOf('const beforeRequest'), source.indexOf('async function processOutput'));
  assert.match(mainRarityPrompt, /protocolForSettings\(settings, loaded\.character\)/);
  assert.match(source, /보조 검사 완료/);
  assert.match(source, /connectionBusy: false/);
  assert.match(source, /async function updateConnectionUi/);
  const connectionHandler = source.slice(source.indexOf('const connect ='), source.indexOf('const auxRun ='));
  assert.match(connectionHandler, /if \(runtime\.connectionBusy\) return/);
  assert.match(connectionHandler, /await updateConnectionUi\(\)/);
  assert.equal(connectionHandler.includes('openRootInventory'), false);
  assert.match(source, /settingChangeBusy: false, auxRecoveryPromise: null/);
  assert.match(source, /보조 모델이 90초 안에 응답하지 않았습니다/);
  assert.match(source, /if \(runtime\.auxRecoveryPromise\) return runtime\.auxRecoveryPromise/);
  assert.match(source, /automaticAuxReady\(ctx\.chat, index, source\)/);
  assert.match(source, /if \(runtime\.auxActive > 0 \|\| runtime\.auxRecoveryPromise\) return/);
  assert.match(source, /runtime\.auxActive === 0 && !runtime\.auxRecoveryPromise/);
  assert.match(source, /await rememberAuxiliaryZero\(ctx, guardKey\)/);
  assert.match(source, /ITEMX context-aware auxiliary regeneration pass/);
  assert.match(source, /TRIGGERING USER TURN/);
  assert.match(source, /RECENT NARRATIVE CONTEXT/);
  assert.match(source, /COMMITTED ASSISTANT OUTPUT \(visible narrative only\)/);
  assert.match(source, /if \(\/itemx\/i\.test\(key\)/);
  assert.match(source, /runtime\.uiRemountAfter = Date\.now\(\) \+ 1200/);
  assert.match(source, /Date\.now\(\) < runtime\.uiRemountAfter/);
  const rootToggleHandler = source.slice(source.indexOf("const toggle = runtime.mainDoc"), source.indexOf("const main = runtime.mainDoc"));
  assert.match(rootToggleHandler, /updateRootSettingButton/);
  assert.equal(rootToggleHandler.includes('openRootInventory'), false);
  assert.equal(rootToggleHandler.includes('recoverAuxiliaryOutput'), false);
  const iframeAuxHandler = source.match(/root\.querySelector\('\[data-action="aux-output"\]'\)[^\n]+/)?.[0] || '';
  assert.equal(iframeAuxHandler.includes('recoverAuxiliaryOutput'), false);
  const auxRunHandler = source.slice(source.indexOf('const auxRun ='), source.indexOf('for (const [key, label] of BADGE_POSITIONS)'));
  assert.match(auxRunHandler, /recoverAuxiliaryOutput\(\{ force: true \}\)/);
  assert.equal(auxRunHandler.includes('openRootInventory'), false);
  assert.match(source, /runButton\.setTextContent\(runtime\.auxActive > 0 \? '처리 중…' : '지금 검사'\)/);
  assert.match(source, /\.itemx2-root-inventory\{display:flex;flex:1;min-height:0;flex-direction:column;overflow:hidden\}/);
  assert.match(source, /\.itemx2-root-inventory>\.itemx-body\{flex:1;min-height:0;overflow-x:hidden;overflow-y:auto/);
  assert.match(source, /itemx2-root-detail-body-\$\{index\}/);
  assert.equal(source.includes('installRootItemDetailClicks'), false);
  assert.match(source, /detail\.setInnerHTML\(itemDetailHtml\(detailItems\[index\]\)\)/);
  assert.match(source, /async function hydrateCheckedItemDetail\(loaded\)/);
  assert.match(source, /querySelector\(`#itemx2-detail-\$\{index\}:checked`\)/);
  assert.match(source, /await delay\(0\);\s*if \(await hydrateCheckedItemDetail\(loaded\)\) return/);
  assert.match(source, /querySelector\(`\.x-risu-\$\{className\}`\)[\s\S]*querySelector\(`\.\$\{className\}`\)/);
  assert.equal(source.includes('renderCard(detailItems[index]'), false);
  assert.match(source, /hasFullCard \? ITEMX_CHAT_STYLE : ITEMX_CHIP_STYLE/);
  assert.match(source, /markerHtmlCache: new Map\(\)/);
  assert.equal(/renderCard\(item, \{ motion: index < 2/.test(source), false);
  const displayHandler = source.slice(source.indexOf('const displayHandler ='), source.indexOf('async function installMainStyle'));
  assert.equal(displayHandler.includes("motion = cards < 2 ? 'full' : 'off'"), false);
  assert.match(displayHandler, /const itemMotion = runtime\.visualEffectsEnabled \? 'full' : 'off'/);
  assert.match(displayHandler, /renderPayload\(`item:\$\{code\}`, payload, itemMotion\)/);
  assert.match(displayHandler, /renderPayload\(`item-ref:\$\{ref\}`, payload, itemMotion\)/);
  assert.match(source, /cachedOrRebuildCurrent\(\)/);
  assert.match(source, /portraitCache: new Map\(\)/);
  assert.match(source, /mainStylePosition === runtime\.badgePosition/);
  assert.match(source, /content-visibility:auto/);
  assert.match(source, /async function installBodyEffectGovernor/);
  assert.equal(source.includes('getBoundingClientRect();\n        const active = rect.bottom'), false);
  assert.match(source, /chattext\.x-risu-itemx-body-scrolling/);
  assert.match(source, /animation-play-state:paused!important/);
  assert.match(source, /itemx2-effects-off/);
  assert.match(source, /itemx-codex-scan\{0%,100%\{opacity:\.2;transform:translate3d/);
  assert.equal(/itemx-codex-scan\{0%,100%\{top:/.test(source), false);
  assert.match(source, /✨ ARCANE SKILL RECORD/);
  assert.match(source, /⚔️ ENCOUNTER ARCHIVE/);
  assert.match(source, /touch-action:pan-y;-webkit-overflow-scrolling:touch/);
  assert.equal(source.includes('registerButton('), false);
  assert.match(source, /registerSetting\('ITEMX CODEX · 권한 및 설정', openSettingsFromRisuMenu/);
  assert.equal(source.includes('requestPermission: false'), false);
  assert.match(source, /requestPluginPermission\('replacer'\)/);
  assert.match(source, /runtime\.permissions\.replacer = permission === true/);
  assert.match(source, /return runtime\.permissions\.replacer/);
  assert.equal(source.includes('itemx2PermissionVersion'), false);
  assert.match(source, /itemx2-native-badge/);
  assert.match(source, /showContainer\(runtime\.compactContainer \? 'floating' : 'fullscreen'\)/);
  assert.match(source, /resizeContainer\(panelHeight, panelWidth\)/);
  assert.match(source, /resizeContainer unavailable; using bounded fullscreen fallback/);
  assert.match(source, /runtime\.compactContainer \? 'floating' : 'fullscreen'/);
  assert.match(source, /itemx-plugin-stage-fallback/);
  assert.match(source, /x-itemx2-badge="launcher"/);
  assert.match(source, /width="48" height="176"/);
  assert.equal(source.includes('<b>INVENTORY</b>'), false);
  assert.match(source, /overflow:\s*hidden/);
  assert.match(source, /@keyframes itemx-plugin-panel-in/);
  assert.match(source, /@keyframes itemx-plugin-panel-out/);
  assert.match(source, /panelOpen: false, panelTransition: 0/);
  assert.match(source, /transition !== runtime\.panelTransition \|\| runtime\.panelOpen/);
  assert.equal(/pluginStorage\.setItem\([^\n]*(panelOpen|inventoryOpen)/.test(source), false);
  const outputPipeline = source.slice(source.indexOf('async function processOutput'), source.indexOf('const afterRequest'));
  assert.equal(outputPipeline.includes('showContainer'), false);
  assert.equal(outputPipeline.includes('hideContainer'), false);
  assert.equal(outputPipeline.includes('recoverAuxiliaryOutput'), false);
  assert.equal(outputPipeline.includes('setTimeout'), false);
  assert.equal(source.includes('persist: true'), false);
  assert.match(source, /await rebuildCurrent\(\);\s*await catchUpLatestOutput/);
  assert.match(source, /automaticAuxSettled\(ctx, index, source\)/);
  assert.match(source, /auxCandidateChecks >= 2/);
  assert.match(source, /async function catchUpLatestOutput\(\)/);
  assert.match(source, /async function repairCommittedTransport\(ctx, index, source\)/);
  assert.match(source, /runtime\.catchUpFingerprint = fingerprint/);
  assert.match(source, /visible-\$\{auxiliarySemanticHash\(source\)\}/);
  assert.match(source, /ITEMX_MESSAGE_EVENT_KEY/);
  assert.match(source, /compactRefMarker\(prefix, ref, payload, domain\)/);
  assert.match(source, /embeddedViewCode/);
  assert.match(source, /inlineViewPayload\(inline, 'item'\)/);
  assert.match(source, /ITEMX CODEX · 기록 복원 중/);
  assert.match(source, /runtime\.catchUpFailedFingerprint = fingerprint/);
  assert.match(source, /runtime\.catchUpRetryAt = Date\.now\(\) \+ Math\.min\(120000/);
  assert.equal(source.includes("settings.auxOutput === 'missing' && sourceEvents.length"), false);
  assert.match(source, /removeRisuReplacer\('beforeRequest', beforeRequest\)/);
  assert.match(source, /removeRisuReplacer\('afterRequest', afterRequest\)/);
  assert.match(source, /validationRegistry = ITEMXCore\.clone\(snapshot\.registry\)/);
  assert.match(source, /setInterval\(\(\) => \{ void catchUpLatestOutput\(\)/);
  assert.match(source, /including an earlier misspelling/);
  assert.match(source, /itemPatch op=merge/);
  assert.match(source, /allowPlugins:\s*false/);
  assert.match(source, /positionMarkersByNarrative/);
  assert.match(source, /preserve every required status\/state\/route trailer/);
  assert.match(source, /itemx-oriental-frame/);
  assert.match(source, /itemx-oriental-seal/);
  assert.match(source, /craft-oriental \.affinity-fx/);
  assert.match(source, /const ITEMXCodex/);
  assert.match(source, /itemx2-tab-skills/);
  assert.match(source, /itemx2-tab-bestiary/);
  assert.match(source, /itemx2-codex-entry-choice/);
  assert.match(source, /ARCANE SKILL RECORD/);
  assert.match(source, /ENCOUNTER ARCHIVE/);
  assert.match(source, /itemx-codex-scan/);
  assert.match(source, /itemx2-codex-detail-row/);
  assert.match(source, /itemsEnabled:\$\{id\}/);
  assert.match(source, /skillsEnabled:\$\{id\}/);
  assert.match(source, /encountersEnabled:\$\{id\}/);
  assert.match(source, /setDomainEnabled/);
  assert.match(source, /enabledCodexDomains/);
  assert.match(source, /Enabled domains: \$\{requested\}/);
  assert.match(source, /기능별 추적/);
  assert.match(source, /무기·아이템/);
  assert.match(source, /전투 도감/);
  assert.match(source, /디버그 진단/);
  assert.match(source, /debugEntries\.length > 30/);
  assert.match(source, /data-action="debug-toggle"/);
  assert.match(source, /ITEMX CODEX · ACTIVE CONTEXT/);
  assert.match(source, /AVAILABLE PORTRAIT ASSET NAMES/);
  assert.match(source, /Risuai\.readImage\(asset\.id\)/);
  assert.match(source, /const ITEMXQuality =/);
  assert.match(source, /state: unresolvedPartials\.length \? 'partial_final' : 'complete'/);
  assert.match(source, /아이템 상세정보 보완 중/);
  assert.ok(source.length < 400000, 'plugin bundle must stay compact with discovery, cleanup and recovery quality controls');
  assert.equal(source.includes('itemx-batch'), false);
  assert.match(source, /runtime\.remountTimer = globalThis\.setInterval/);
  assert.match(source, /\}, 1200\)/);
  assert.match(source, /createMutationObserver/);
  assert.equal(source.includes('hostSettingsTimer'), false);
  const ensureRoot = source.slice(source.indexOf('async function ensureRootInventory'), source.indexOf('async function loadCodexPortraits'));
  assert.ok(ensureRoot.indexOf('const active = await context()') < ensureRoot.indexOf('runtime.auxActive > 0'));
  assert.match(source, /async function resetRuntimeForContext\(active\)/);
  const resetRuntime = source.slice(source.indexOf('async function resetRuntimeForContext'), source.indexOf('async function ensureRootInventory'));
  assert.equal(resetRuntime.includes('runtime.eventPayloads = new Map()'), false);
  assert.match(resetRuntime, /refreshLatest\(active\?\.chat/);
  assert.match(source, /runtime\.markerHtmlCache\.clear\(\)/);
  assert.match(source, /runtime\.lastDomError/);
  assert.match(source, /await delay\(300\)/);
  assert.equal(source.includes("registerSetting('ITEMX CODEX · 설정', () => openInventory('settings')"), false);
  assert.equal(source.includes("showContainer('fullscreen')"), false);
  assert.match(source, /async function openRootInventory/);
  assert.match(source, /x-itemx2-drawer/);
  assert.match(source, /pointer-events:none/);
  assert.match(source, /await doc\.createElement\('style'\)/);
  const rootInventory = source.slice(source.indexOf('async function openRootInventory'), source.indexOf('function matches'));
  assert.equal(rootInventory.includes('showContainer'), false);
  assert.equal(rootInventory.includes("'fullscreen'"), false);
  assert.match(source, /button\[aria-label="ITEMX"\]/);
  assert.match(source, /badgePosition/);
  assert.match(source, /좌하/);
  assert.match(source, /우상/);
  assert.match(source, /await runtime\.rootDrawer\.addClass\(`x-risu-itemx2-pos-\$\{key\}`\)/);
  assert.match(source, /drawerAttached = Boolean\(await runtime\.rootDrawer\.getParent\(\)\)/);
  assert.match(source, /styleAttached = Boolean\(await runtime\.mainStyle\.getParent\(\)\)/);
  assert.equal(source.includes('const positionControls ='), false);
  assert.equal(source.includes('itemx2-root-open"'), false);
  assert.match(source, /async function setRootOpen\(open\)/);
  const badgeClick = source.slice(source.indexOf('const routeBadge = async'), source.indexOf('const routeControls = async'));
  assert.ok(badgeClick.indexOf('await setRootOpen(true)') < badgeClick.indexOf('cachedOrRebuildCurrent()'));
  assert.match(badgeClick, /runtime\.rootContentReady && cacheReady/);
  const removeRoot = source.slice(source.indexOf('async function removeRootClickRouter'), source.indexOf('async function mountRootLoading'));
  assert.ok(removeRoot.indexOf('await removeRootClickRouter()') < removeRoot.indexOf('await runtime.rootDrawer.remove()'));
  assert.match(source, /target\.matches\('\[x-itemx2-drawer="owner"\], \[x-itemx2-drawer="owner"\] \*'\)/);
  assert.match(source, /const lookup = buildMessageEventLookup\(latestChat\)/);
  assert.match(source, /const regionUpdated = attached && open && runtime\.rootContentReady && await updateRootRegions\(html\)/);
  assert.match(source, /attached = Boolean\(await root\.getParent\(\)\)/);
  assert.match(source, /if \(!attached\) \{\s*await removeRootDrawer\(\)/);
  assert.match(source, /await setRootOpen\(false\)/);
  assert.match(source, /itemx2-root-drawer\.itemx2-is-open \.itemx2-root-panel/);
  const positionHandler = source.slice(source.indexOf('for (const [key, label] of BADGE_POSITIONS)'), source.indexOf("const toggle = runtime.mainDoc"));
  assert.equal(positionHandler.includes('installMainStyle'), true);
  assert.equal(positionHandler.includes('openRootInventory'), false);
  assert.match(source, /data-tab="settings"/);
  assert.match(source, /enabled: enabled !== '0'/);
  const bootstrap = source.slice(source.lastIndexOf('await loadBadgePosition()'), source.indexOf('await Risuai.onUnload'));
  assert.ok(bootstrap.indexOf('registerSetting(') < bootstrap.indexOf('const initial = await context()'));
  assert.ok(bootstrap.indexOf('const initial = await context()') < bootstrap.indexOf('connected = await installPipelineHooks()'));
  assert.match(bootstrap, /runtime\.status = '채팅 진입 대기'/);
  assert.match(source, /const styled = await installMainStyle\(\)/);
  assert.match(source, /getRootDocument\(/);
  assert.match(source, /setChatToIndex\(/);
  assert.match(source, /현재 채팅 ITEMX 기록 제거/);
  assert.match(source, /async function cleanCurrentChatItemx\(\)/);
  assert.match(source, /const CHAT_DATA_KEYS = \[/);
  assert.match(source, /await setEnabled\(ctx\.character, false\)/);
  assert.match(source, /runtime\.cleanupArmedUntil = Date\.now\(\) \+ 7000/);
  assert.match(source, /function reconcileStoredRefViews\(chat, preferredLatestIndex = null\)/);
  assert.match(source, /const keepInline = index === latestIndex/);
  assert.match(source, /\.chattext \.x-risu-itemx-card/);
  assert.equal(source.includes('__ITEMX_'), false);
  assert.equal(source.includes('{{moduleenabled'), false);
  assert.equal(source.includes('risu-trigger='), false);
});

test('preview uses the same renderer source as the plugin', async () => {
  const preview = await readFile(resolve(root, 'dist/itemx2-preview.html'), 'utf8');
  assert.match(preview, /ITEMXRenderer\.renderCard/);
  assert.match(preview, /ITEMXRenderer\.renderTile/);
  assert.match(preview, /단일 속성/);
  assert.match(preview, /다중 속성/);
});
